title: Kaijie He's Homepage
page-top-title: Kaijie He
top-section-bg-text: Informatics and Data Science
home-subtitle: Kaijie He&ensp;|&ensp;何凱傑
copyright-text: '&copy; Kaijie He 2026. All Rights Reserved.'
